//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportMaintenanceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignTask
    {
        public int AssignTaskId { get; set; }
        public string Task { get; set; }
        public string Staff { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
