//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportMaintenanceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.AssignTasks = new HashSet<AssignTask>();
        }
    
        public int OperationId { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignTask> AssignTasks { get; set; }
    }
}
